# Generated by Django 5.2.4 on 2025-11-01 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Motivos de solicitação do suporte',
            },
        ),
        migrations.CreateModel(
            name='RequisicaoSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RESOLVIDO', 'Resolvido'), ('EM_ANDAMENTO', 'Em andamento'), ('NAO_ANALISADO', 'Não analisado')], max_length=20)),
                ('descricao', models.TextField()),
                ('foto', models.FileField(blank=True, null=True, upload_to='usuario/requisicao')),
                ('motivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suporte.motivosuporte')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
