# Generated by Django 5.2.4 on 2025-12-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisicaosuporte',
            options={'ordering': ['status']},
        ),
        migrations.AlterField(
            model_name='requisicaosuporte',
            name='status',
            field=models.CharField(choices=[('RESOLVIDO', 'Resolvido'), ('EM_ANDAMENTO', 'Em andamento'), ('NAO_ANALISADO', 'Não analisado')], default='NAO_ANALISADO', max_length=20),
        ),
    ]
