# Generated by Django 5.2.4 on 2025-12-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0002_alter_requisicaosuporte_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaosuporte',
            name='assunto',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
