# Generated by Django 5.2.4 on 2025-12-02 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0003_requisicaosuporte_assunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicaosuporte',
            name='assunto',
        ),
    ]
