# Generated by Django 5.2.4 on 2025-09-13 21:13

import app.functions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corRGB', models.CharField(max_length=13)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MotivoSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.TextField(verbose_name='descrições')),
                ('etiquetas', models.ManyToManyField(related_name='comunidades', to='app.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_post', models.CharField(max_length=400)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuario/posts')),
                ('curtidas', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField()),
                ('comunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comunidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField()),
                ('conteudo', models.TextField()),
                ('usuario', models.ForeignKey(default=app.functions.get_usuario_padrao, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post')),
            ],
        ),
        migrations.CreateModel(
            name='RequisicaoSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RESOLVIDO', 'Resolvido'), ('EM_ANDAMENTO', 'Em andamento'), ('NAO_ANALISADO', 'Não analisado')], max_length=20)),
                ('descricao', models.TextField()),
                ('foto', models.FileField(blank=True, null=True, upload_to='usuario/requisicao')),
                ('motivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.motivosuporte')),
            ],
        ),
    ]
