# Generated by Django 5.2.4 on 2025-09-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidade',
            name='capa_comunidade',
            field=models.FileField(default=1, upload_to='comunidade/capa'),
            preserve_default=False,
        ),
    ]
