# Generated by Django 5.2.4 on 2025-09-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='ext',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
