# Generated by Django 5.2.4 on 2025-09-14 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comunidade_capa_comunidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidade',
            name='membros',
            field=models.ManyToManyField(related_name='comunidades', to=settings.AUTH_USER_MODEL),
        ),
    ]
