# Generated by Django 5.2.4 on 2025-09-24 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_arquivo_titulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tematica', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('url_da_reuniao', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('comunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comunidade')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
