# Generated by Django 5.2.4 on 2025-09-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_reuniao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='descricao',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
