# Generated by Django 5.2.4 on 2025-09-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_reuniao_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reuniao',
            old_name='data',
            new_name='data_hora',
        ),
    ]
