# Generated by Django 5.2.4 on 2025-10-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_data_reuniao_data_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descricao_post',
            new_name='conteudo',
        ),
    ]
