# Generated by Django 5.2.4 on 2025-10-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_curtida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='curtidas',
        ),
    ]
