# Generated by Django 5.2.4 on 2025-10-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_post_curtidas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curtida',
        ),
    ]
