# Generated by Django 5.2.4 on 2025-10-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_curtida'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidade',
            name='nivel_ensino',
            field=models.CharField(choices=[('ENSINO_TECNICO', 'Ensino técnico'), ('ENSINO_FUNDAMENTAL_I', 'Ensino fundamental I'), ('ENSINO_MEDIO', 'Ensino médio'), ('ENSINO_SUPERIO', 'Ensino superior'), ('PRE_ESCOLAR', 'Pré-escola'), ('OUTRO', 'Outro'), ('DEFAULT', 'Não aplicado')], default='DEFAULT', max_length=50),
        ),
    ]
