# Generated by Django 5.2.4 on 2025-10-11 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_comunidade_nivel_ensino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidade',
            name='nivel_ensino',
        ),
    ]
