# Generated by Django 5.2.4 on 2025-11-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_comunidade_nivel_ensino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicaosuporte',
            name='motivo',
        ),
        migrations.DeleteModel(
            name='MotivoSuporte',
        ),
        migrations.DeleteModel(
            name='RequisicaoSuporte',
        ),
    ]
