# Generated by Django 5.2.4 on 2025-12-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_requisicaosuporte_motivo_delete_motivosuporte_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reuniao',
            options={'verbose_name_plural': 'Reuniões'},
        ),
    ]
