# Generated by Django 5.2.4 on 2025-12-02 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_reuniao_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidade',
            name='membros',
            field=models.ManyToManyField(null=True, related_name='comunidades', to=settings.AUTH_USER_MODEL),
        ),
    ]
