# Generated by Django 5.2.4 on 2025-07-28 23:29

import autenticacao.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=autenticacao.functions.caminho_imagem),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pontuacao',
            field=models.FloatField(blank=True, default=3, null=True),
        ),
    ]
