# Generated by Django 5.2.4 on 2025-07-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_alter_usuario_biografia_alter_usuario_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.BooleanField(unique=True),
        ),
    ]
