# Generated by Django 5.2.4 on 2025-08-22 00:09

import autenticacao.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.FileField(default=1, upload_to=autenticacao.functions.caminho_imagem),
            preserve_default=False,
        ),
    ]
