# Generated by Django 5.2.4 on 2025-08-22 01:05

import autenticacao.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(upload_to=autenticacao.functions.caminho_imagem),
        ),
    ]
