# Generated by Django 5.2.4 on 2025-08-22 01:56

import autenticacao.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0008_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teste',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.FileField(upload_to=autenticacao.functions.caminho_imagem),
        ),
    ]
