# Generated by Django 5.2.4 on 2025-08-31 00:49

import autenticacao.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0009_delete_teste_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.FileField(default='static/img/defaultFotoPerfil.jpg', upload_to=autenticacao.functions.caminho_imagem),
        ),
    ]
