# Generated by Django 5.2.4 on 2025-09-04 10:41

import autenticacao.functions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0010_alter_usuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.FileField(default='usuario/foto/defaultFotoPerfil.jpg', upload_to=autenticacao.functions.caminho_imagem),
        ),
        migrations.CreateModel(
            name='PerguntasQuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_pergunta', models.CharField(max_length=40)),
                ('texto_Pergunta', models.CharField(max_length=700)),
                ('tipo_input', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autenticacao.inputs')),
            ],
        ),
        migrations.CreateModel(
            name='PerguntasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=500)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.perguntasquestionario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
