# Generated by Django 5.2.4 on 2025-09-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0011_inputs_alter_usuario_foto_perguntasquestionario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSaber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='Inputs',
            new_name='Input',
        ),
        migrations.RenameModel(
            old_name='PerguntasQuestionario',
            new_name='PerguntaDoQuestionario',
        ),
        migrations.RenameModel(
            old_name='PerguntasUsuario',
            new_name='PerguntaUsuario',
        ),
    ]
