# Generated by Django 5.2.4 on 2025-09-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0012_areasaber_rename_inputs_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntadoquestionario',
            name='placeHolder',
            field=models.CharField(default='', max_length=50),
        ),
    ]
