# Generated by Django 5.2.4 on 2025-09-04 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0013_perguntadoquestionario_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='OpcoesPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autenticacao.opcao')),
            ],
        ),
        migrations.DeleteModel(
            name='AreaSaber',
        ),
        migrations.RenameField(
            model_name='perguntadoquestionario',
            old_name='placeHolder',
            new_name='placeholder',
        ),
        migrations.RenameField(
            model_name='perguntadoquestionario',
            old_name='texto_Pergunta',
            new_name='texto_pergunta',
        ),
        migrations.AddField(
            model_name='opcoespergunta',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.perguntadoquestionario'),
        ),
    ]
