# Generated by Django 5.2.4 on 2025-09-04 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0014_opcao_opcoespergunta_delete_areasaber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcao',
            name='pergunta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autenticacao.perguntadoquestionario'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OpcoesPergunta',
        ),
    ]
