# Generated by Django 5.2.4 on 2025-09-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0015_opcao_pergunta_delete_opcoespergunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntadoquestionario',
            name='placeholder',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
