# Generated by Django 5.2.4 on 2025-09-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0016_alter_perguntadoquestionario_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntadoquestionario',
            name='placeholder',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
    ]
