# Generated by Django 5.2.4 on 2025-09-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0018_materialusuados'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialUsuados',
            new_name='MaterialUsuarios',
        ),
    ]
