# Generated by Django 5.2.4 on 2025-09-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0019_rename_materialusuados_materialusuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome_completo',
        ),
        migrations.AddField(
            model_name='perguntadoquestionario',
            name='aparecer_no_perfil',
            field=models.BooleanField(default=True),
        ),
    ]
