# Generated by Django 5.2.4 on 2025-09-27 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0020_remove_usuario_biografia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialUsuarios',
            new_name='PergutasCheckBox',
        ),
    ]
