# Generated by Django 5.2.4 on 2025-10-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0021_rename_materialusuarios_pergutascheckbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pontuacao',
            field=models.FloatField(blank=True, default=2, null=True),
        ),
    ]
