# Generated by Django 5.2.4 on 2025-11-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0022_alter_usuario_pontuacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcao',
            options={'ordering': ['pergunta'], 'verbose_name_plural': 'Opções dos inputs'},
        ),
        migrations.AlterModelOptions(
            name='perguntausuario',
            options={'ordering': ['user'], 'verbose_name_plural': 'Respostas únicas do questionario'},
        ),
        migrations.AlterModelOptions(
            name='pergutascheckbox',
            options={'ordering': ['usuario'], 'verbose_name_plural': 'respostas com mais de uma opção'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['email']},
        ),
    ]
